[versions]
assertk = "0.28.0"
junit = "5.10.2"
kotlinxSerialization = "1.6.3"

[libraries]
assertk_core = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
junit_jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
kotlinx_serialization_json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
